trvgcy/checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('checkout/<int:trip_id>', views.checkout, name='checkout')
]

trvgcy/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
]

trvgcy/trips/urls.py
from django.urls import path

from . import views

app_name = 'trips'

urlpatterns = [
    path('listing/', views.listing, name='listing'),
    path('trip/<int:trip_id>/', views.trip, name='trip'),
    path('builder/', views.builder.as_view(), name='builder')
]

trvgcy/trvgcy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pages import views

urlpatterns = [
    path('', include('checkout.urls')),
    path('', include('trips.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('api/users',views.UserList.as_view())
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trvgcy/checkout/models.py
from django.db import models

# Create your models here.

trvgcy/pages/models.py
from django.db import models

# Create your models here.

class UserAccount(models.Model):

# Fields

    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=12, unique=True)
    password = models.CharField(max_length=12)
    email = models.EmailField(max_length=30, unique = True)
    is_active = models.BooleanField(default=False)

# Metadata

# Methods

    def __str__(self):
        return self.username

trvgcy/checkout/views.py
from django.shortcuts import render

# Create your views here.


def checkout(request, trip_id):
    return render(request, 'checkout/checkout.html')

trvgcy/templates/partials/_Navbar.html
<!-- called by: base.html -->
{% load static %}

<nav class="navbar navbar-expand-md navbar-light fixed-top py-0.5" id="main-nav">
    <div class="container">
        <a class="navbar-brand">
            <img src= "{% static "pages/img/logo.png" %}" width="50" height="50" alt="">
            <h3 class="d-inline align-middle">Python Travels</h3>
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
<!--                <li class="nav-item">
                    <a href="#home" class="nav-link">Home</a>
                </li> -->
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" href="{% url 'pages:index' %}">&nbsp; &nbsp;
                        <i class="fas fa-home"></i>
                        <br>Home
                    </a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" href="#loginModal" data-toggle="modal" data-target="#loginModal" style="text-align: center;">
                        <i class="far fa-user-circle" style="text-align: center;"></i>
                        <br>Login
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#contactModal" data-toggle="modal" data-target="#contactModal" class="nav-link">Contact</a>
                </li>
           </ul>
        </div>
        <!-- LOGIN MODAL TRIGGER
        <button class="btn btn-dark" data-toggle="modal" data-target="#loginModal">Login</button>
        -->
   </div>
</nav>

{% include 'partials/_contactModal.html' %}
{% include 'partials/_loginModal.html' %}

trvgcy/templates/partials/_checkout.html
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6 text-center"><img class="rounded img-fluid border p-2" src="#" width="200px" height="150px"></div>
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <p><strong>Flights</strong></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p>Go:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span>Text</span></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p>Return:&nbsp; &nbsp; &nbsp; &nbsp;<span>Text</span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6 text-center"><img class="rounded img-fluid border p-2" src="#" width="200px" height="150px"></div>
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <p><strong>Hotel</strong></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p>Hotel Esmeralda tal</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6 text-center"><img class="rounded img-fluid border p-2" src="#" width="200px" height="150px"></div>
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <p><strong>Events</strong></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p>Europa Park</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <p>Travellers</p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p>&nbsp;2</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <p>Flights Cost</p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p><i class="fa fa-eur"></i>&nbsp;2</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <p>Hotel Cost</p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p><i class="fa fa-eur"></i>&nbsp;2</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <p>Events Cost</p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p><i class="fa fa-eur"></i>&nbsp;2</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <p>VAT (5%)</p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p><i class="fa fa-eur"></i>&nbsp;2</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col">
                                <p style="font-size: 20px;"><strong>Total</strong></p>
                            </div>
                            <div class="col" style="text-align: right;">
                                <p style="font-size: 20px;"><i class="fa fa-eur"></i>&nbsp;<strong>2</strong></p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col text-center"><button class="btn btn-outline-primary" type="button"><i class="fa fa-backward"></i>&nbsp;Back to Trip</button></div>
                            <div class="col text-center" style="text-align: right;"><button class="btn btn-outline-primary text-left" type="button">Add to WishList</button></div>
                            <div class="col"><button class="btn btn-primary btn-block" type="button" style="background-color: rgb(59,79,101);"><i class="fa fa-paypal"></i>&nbsp;Pay Now</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

trvgcy/templates/partials/_contactModal.html
<div class="modal" id="contactModal">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Contact us</h5>
            <button class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus unde veniam harum magnam molestias dignissimos omnis
            architecto, quod, obcaecati dolorum debitis dolore porro qui, iusto quo accusantium voluptates pariatur illo.
          </div>
          <div class="modal-footer">
            <button class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
    </div>
</div>

trvgcy/templates/partials/_listtrips.html
<div class="mt-4">
    <div class="container">
        <h1>Heading</h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 row-cols-xl-4 m-3" style="height: 348px;">
            {% if thetrips %}
                {% for trip in thetrips %}
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-4">
                        <div class="card border-primary shadow">
                            <img class="card-img-top w-100 d-block" src="{{trip.photo_main.url}}">
                            <div class="card-body">
                                <h4 class="card-title oneline">{{trip.comercial_reference}}</h4>
                                <h6 class="text-muted card-subtitle mb-2">{{trip.marketing_message}}</h6>
                                <p class="card-text oneline">{{trip.main_description}}</p>
                                <div class="row">
                                    <div class="col">
                                        <a href ="{% url 'trips:trip' trip.id %}" class="btn btn-outline-primary btn-block" type="button" style="color: rgb(39,111,13);">More details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <p>No Trips Available</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>

trvgcy/templates/partials/_newaccountModal.html
{% block javascript %}
  <script>
    $("#id_username").change(function () {
      console.log( $(this).val() );
    });
  </script>
{% endblock %}

<div class="modal" id="newaccountModal">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create New Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class = "modal-body">
                <form role ="form" id = "modal_form"
                    method="post"
                    oninput='password2.setCustomValidity(password2.value != password.value ?
                            "Passwords do not match.": "")'
                    action="#">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input class="form-control" type="text" placeholder="Username" name="username"
                                                                                       id="id_username">
                    </div>
                    <div class="form-group">
                        <label for="email">email ID</label>
                        <input class="form-control" type="email" placeholder="Enter your email" name="email"
                                                                                                id="id_email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input class="form-control" type="password" placeholder="Password" name="password">
                    </div>
                    <div class="form-group">
                        <label for="password2">Re-Type Password</label>
                        <input class="form-control" type="password" placeholder="Re-Type Password" name="password2">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">Create account</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

trvgcy/templates/partials/_searchingForm.html
<!-- called by: pages/index.html -->
<section id="search" class="bg-dark text-white py-2">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    <form action="{% url 'pages:search' %}" class="search-trip" method = "get">
                        <div class="row">
                            <div class="col-lg align-items-end">
                                <div class="form-group">
                                    <label for="destination">Destination</label>
                                    <div class="form-field">
                                        <div class="icon"><span class="ion-ios-search"></span></div>
                                        <input type="text" class="form-control" name="destination" placeholder="Search place">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg align-items-end">
                                <div class="form-group">
                                    <label for="checkin">Check-in date</label>
                                    <div class="input-group date" id="datetimepicker7" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input" name ="checkin" data-target="#datetimepicker7"/>
                                        <div class="input-group-append" data-target="#datetimepicker7" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg align-items-end">
                                <div class="form-group">
                                    <label for="checkout">Check-out date</label>
                                    <div class="input-group date" id="datetimepicker8" data-target-input="nearest">
                                        <input type="text" class="form-control datetimepicker-input" name = "checkout" data-target="#datetimepicker8"/>
                                        <div class="input-group-append" data-target="#datetimepicker8" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg align-items-end">
                                    <div class="form-group">
                                    <label for="max_price">Price Limit</label>
                                    <div class="form-field">

                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                            <label class = "sr-only">price</label>
                                            <select name ="max_price" class="form-control">
                                               <option selected="true" disabled="disabled"> Price (All)</option>
                                               {% for key,value in price_limit.items %}
                                                    <option value="{{ key }}">{{ value }}</option>
                                               {% endfor %}
                                            </select>

                                    </div>
                                </div>
                            </div>
                            <div class="col-lg align-self-end">
                                <div class="form-group">
                                    <div class="form-field">
                                        <input type="submit" value="Search" class="form-control btn btn-primary">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

trvgcy/templates/partials/_searchresult.html
<div class="mt-4">
    <div class="container">
        <h1>Heading</h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 row-cols-xl-4 m-3" style="height: 348px;">
            {% if results %}
                {% for trip in results %}
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-4">
                        <div class="card border-primary shadow">
                            <img class="card-img-top w-100 d-block" src="{{trip.photo_main.url}}">
                            <div class="card-body">
                                <h4 class="card-title oneline">{{trip.comercial_reference}}</h4>
                                <h6 class="text-muted card-subtitle mb-2">{{trip.marketing_message}}</h6>
                                <p class="card-text oneline">{{trip.main_description}}</p>
                                <div class="row">
                                    <div class="col">
                                        <a href ="{% url 'trips:trip' trip.id %}" class="btn btn-outline-primary btn-block" type="button" style="color: rgb(39,111,13);">More details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <p>No Trips Available</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>

trvgcy/templates/partials/_showCaseSlider.html
<!-- SHOWCASE SLIDER -->
{% load static %}
<section id="showcase">
    <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for trip in thetrips %}
            {% if forloop.first %}
                <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}" class="active"></li>
            {% else %}
                <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}"></li>
            {% endif %}
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for trip in thetrips %}
            {% if forloop.first %}
            <div class="carousel-item active" style="background-image:url({{trip.photo_index.url}});
                                                     background-size: cover; " >
                 <div class="container">
                    <div class="carousel-caption d-none d-sm-block text-right mb-5">
                        <h1 class="display-3">{{ trip.comercial_reference }}</h1>
                        <p class="lead">{{ trip.marketing_message }}
                            </p>
                        <a href="{% url 'trips:trip' trip.id %}" class="btn btn-danger btn-lg">More details</a>
                    </div>
                 </div>
            </div>
            {% else %}
            <div class="carousel-item" style="background-image:url({{trip.photo_index.url}});
                                              background-size: cover; " >
                <div class="container">
                    <div class="carousel-caption d-none d-sm-block text-right mb-5">
                        <h1 class="display-3">{{ trip.comercial_reference }}</h1>
                        <p class="lead">{{ trip.marketing_message }}
                           </p>
                        <a href="{% url 'trips:trip' trip.id %}" class="btn btn-primary btn-lg">More details</a>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <a href="#myCarousel" data-slide="prev" class="carousel-control-prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a href="#myCarousel" data-slide="next" class="carousel-control-next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</section>

trvgcy/templates/partials/_tripdetails.html
<div class="container">
    <div class="row mt-4"></div>
    <div class="row mt-4">
        <div class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8">
            <div class="carousel slide carousel-fade" data-ride="carousel" id="carousel-1">
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active"><img class="w-100 d-block" src="{{thetrip.photo_main.url}}" alt="Slide Image"></div>
                    <div class="carousel-item"><img class="w-100 d-block" src="{{thetrip.img_1.url}}" alt="Slide Image"></div>
                    <div class="carousel-item"><img class="w-100 d-block" src="{{thetrip.img_2.url}}" alt="Slide Image"></div>
                </div>
                <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                        <span class="sr-only">Previous</span>
                     </a>
                     <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
                         <span class="carousel-control-next-icon"></span>
                         <span class="sr-only">Next</span>
                     </a>
                </div>
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-1" data-slide-to="1"></li>
                        <li data-target="#carousel-1" data-slide-to="2"></li>
                    </ol>
            </div>
            <hr>
            <div class="row mb-5 thumbs">
                <div class="col-md-2">

            <a href="{{thehotel.photo_main.url}}" data-lightbox="hotel">
                <img src="{{thehotel.photo_main.url}}" alt="" class="img-fluid">
            </a>

                </div>
                <div class="col-md-2">
            <a href="{{thehotel.photo1.url}}" data-lightbox="hotel">
                <img src="{{thehotel.photo1.url}}" alt="" class ="img-fluid">
            </a>

                </div>
                <div class="col-md-2">

            <a href="{{thehotel.photo2.url}}" data-lightbox="hotel">
                <img src="{{thehotel.photo2.url}}" alt="" class ="img-fluid">
            </a>

                </div>
            </div>
            <hr>
            <div class="row mb-5 thumbs">
                <div class="col-md-2">
                    <a href="{{thevent.photo_main.url}}" data-lightbox="event">
                        <img src="{{thevent.photo_main.url}}" alt ="" class="img-fluid">
                    </a>
                </div>
                <div class="col-md-2">
                    <a href="{{thevent.photo1.url}}" data-lightbox="event">
                        <img src="{{thevent.photo1.url}}" alt ="" class="img-fluid">
                    </a>
                </div>
                <div class="col-md-2">
                    <a href="{{thevent.photo2.url}}" data-lightbox="event">
                        <img src="{{thevent.photo2.url}}" alt ="" class="img-fluid">
                    </a>
                </div>
            </div>
            <hr>
        </div>
        <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4">
            <h2><strong>{{ thetrip.comercial_reference }}</strong></h2>
            <h3 style="font-size: 20px;">{{ thetrip.main_description }}</h3>
            <div>
                <p style="font-size: 24px;"><i class="fa fa-euro" style="font-size: 24px;"></i>&nbsp;<strong>{{thetrip.basic_price}}</strong>
                    <br>
                    <span style="color: rgb(47,177,99);font-size: 16px;">{{thetrip.marketing_message}}</span></p>
            </div>
            <div><button class="btn btn-primary" type="button">Button</button></div>
            <div class="mt-3">
                <form>
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <label class="custom-control-label" for="formCheck-1">opcion1</label>
                            <input class="custom-control-input" type="radio" id="formCheck-1" name="choise" value="option_1">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <label class="custom-control-label" for="formCheck-3">opcion2</label>
                            <input class="custom-control-input" type="radio" id="formCheck-2" name="choise" value="option_2">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-radio">
                            <label class="custom-control-label" for="formCheck-2">opcion3</label>
                            <input class="custom-control-input" type="radio" id="formCheck-3" name="choise" value="option_3">
                        </div>
                    </div>
                </form>
            </div>
            <div>
                <button href ="{% url 'checkout:checkout' thetrip.id %}" class="btn btn-primary btn-block" type="button">
                    <i class="fa fa-star"></i>Button</button></div>
            <div>
                <p class="m-2">{{ thetrip.secondary_description }}<br><br></p>
            </div>
        </div>
    </div>
</div>

<div class="container mt-3">
    <div>
        <ul class="nav nav-pills nav-justified shadow">
            <li class="nav-item">
                <a class="nav-link" role="tab" data-toggle="pill" href="#tab-1"><i class="fa fa-star"></i>Opción 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" role="tab" data-toggle="pill" href="#tab-2"><i class="fa fa-star"></i>Opción 2</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade" role="tabpanel" id="tab-1">
                <div class="table-responsive mt-3">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Column 1</th>
                            <th>Column 2</th>
                            <th>Column 3</th>
                            <th>Column 4</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Cell 1</td>
                            <td>Cell 2</td>
                            <td>Cell 3</td>
                            <td>Cell 4</td>
                        </tr>
                        <tr>
                            <td>Cell 5</td>
                            <td>Cell 6</td>
                            <td>Cell 7</td>
                            <td>Cell 8</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tab-pane fade show active" role="tabpanel" id="tab-2">
                <p class="mt-4">Paragraph</p>
                <p><strong>Paragraph</strong></p>
                <p>Paragraph</p>
                <p><strong>Paragraph</strong></p>
                <p>Paragraph</p>
                <p><strong>Paragraph</strong></p>
                <p>Paragraph</p>
                <p><strong>Paragraph</strong></p>
                <p>Paragraph</p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-2 text-center"><img class="rounded img-fluid shadow p-2" style="text-align: center;width: 150;height: 150;" src="#"></div>
        <div class="col">
            <p><strong>User Name&nbsp;</strong><span style="color: rgb(23,188,30);"><i class="material-icons" style="color: rgb(26,197,43);">verified_user</i>Verified User</span></p>
            <p>Paragraph</p>
        </div>
    </div>
</div>